### ISSUE TITLE
petit: traceback if reading file fails due to permission errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crunchtools/petit#1]
```
Hi,

A Debian user (Michael Prokop <mika@debian.org>) encountered a bug with Petit : 

-----8<-----

Package: petit
Version: 1.0.3-1
Severity: normal


% petit --hash  ~log/syslog
Traceback (most recent call last):
  File "/usr/bin/petit", line 348, in <module>
    get_options(sys.argv[1:])
  File "/usr/bin/petit", line 135, in get_options
    hash(filename)
  File "/usr/bin/petit", line 164, in hash
    log = Log(args)
  File "/usr/share/petit/crunchtools.py", line 620, in __init__
    buffer = self.open_file(filename)
  File "/usr/share/petit/crunchtools.py", line 649, in open_file
    f = open(filename)                         
IOError: [Errno 13] Permission denied: '/var/log/syslog'

According exception handling without displaying the
traceback to the user would be nice. :)

regards,
-mika-

-----8<-----
The complete Debian bug report is available here : 
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=588900

Best regards,
Carl Chenet - Debian maintainer

Blog: http://carlchenet.wordpress.com
Identi.ca: http://identi.ca/carlchenet

```

Original issue reported on code.google.com by `cha...@ohmytux.com` on 15 Jul 2010 at 1:30

**Comment by fatherlinux** [comment]
Fixed in e74f8e2 (#22): read_source() turns OSError into a one-line 'petit: cannot read <file>: Permission denied' and exits 1. Duplicate of #16.
