### ISSUE TITLE
Petit crashes when parsing /var/log/syslog on Debian

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crunchtools/petit#2]
```
Hi,

One of the Debian users has the following issue : 

---8<---
Hi,

I have a crash while using --hash with the /var/log/syslog file :

bureau:~# petit --hash /var/log/syslog
Traceback (most recent call last):
  File "/usr/bin/petit", line 348, in <module>
    get_options(sys.argv[1:])
  File "/usr/bin/petit", line 135, in get_options
    hash(filename)
  File "/usr/bin/petit", line 164, in hash
    log = Log(args)
  File "/usr/share/petit/crunchtools.py", line 631, in __init__
    self.append(Entry(line))
  File "/usr/share/petit/crunchtools.py", line 87, in __init__
    self.hour, self.minute, self.second = clocktime.split(":") 
ValueError: need more than 1 value to unpack

Bye,
Carl Chenet
---8<---

The original bug report is available at 
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=589691

Bye,
Carl Chenet - Debian maintainer

Blog: http://carlchenet.wordpress.com
Identi.ca: http://identi.ca/carlchenet

```

Original issue reported on code.google.com by `cha...@ohmytux.com` on 20 Jul 2010 at 2:30

**Comment by fatherlinux** [comment]
Fixed in 4.0.0 (#34). The 2010 crash came from `SyslogEntry` hitting a line whose third field wasn't `HH:MM:SS` (e.g. `-- MARK --` or a truncated line) and letting the `ValueError` escape. Since 4.0.0, `CrunchLog._build` catches a driver's parse failure and falls back to `RawEntry` for the whole run, flagging the result as `degraded`; `--strict` / `strict=True` keeps the old fail-fast behaviour as a clean `ParseError` instead of a traceback. Covered by `test/test_api.py` (degraded-path tests).

Verified on 4.1.1: `petit --hash` over a syslog file mixing valid lines with `-- MARK --` and a line missing its clock field exits 0 and hashes every line.
