### ISSUE TITLE
Crashes on large files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crunchtools/petit#5]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?

[root@zoltan ~]# (zcat /var/log/snmpd.log.[1-9].gz; cat
/var/log/snmpd.log) | grep `date -d 'last month' | awk '{print $2}'`|
grep "snmpd\[" | petit --hash
Traceback (most recent call last):
File "/usr/bin/petit", line 348, in ?
get_options(sys.argv[1:])
File "/usr/bin/petit", line 135, in get_options
hash(filename)
File "/usr/bin/petit", line 164, in hash
log = Log(args)
File "/usr/share/petit/crunchtools.py", line 631, in __init__
self.append(Entry(line))
File "/usr/share/petit/crunchtools.py", line 90, in __init__
self.month = str(time.strptime(self.month,"%b")[1])
File "/usr/lib/python2.4/_strptime.py", line 291, in strptime
found = format_regex.match(data_string)
MemoryError

Please use labels and text to provide additional information.
Scott submitted this, I know what it is


```

Original issue reported on code.google.com by `scott.mccarty@gmail.com` on 28 Apr 2011 at 6:23

**Comment by fatherlinux** [comment]
Replaced by #38. The traceback here is from the pre-rewrite Python 2.4 code, but the underlying problem (the whole input held in memory) still exists, and #38 tracks the fix. The repro from this issue has been copied there.
